language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

install:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - cargo build
  - cargo test
