[package]
name = "id3"
version = "1.3.0"
edition = "2021"
authors = [
    "polyfloyd <floyd@polyfloyd.net>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/polyfloyd/rust-id3"
description = "A library for reading and writing ID3 metadata"
keywords = ["id3", "mp3", "wav", "aiff", "metadata"]
categories = ["encoding", "multimedia", "multimedia::audio", "parser-implementations",]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]

[dependencies]
bitflags = "1.3"
byteorder = "1.4"
flate2 = "1"
document-features = "0.2"

[dev-dependencies]
tempfile = "3"

[features]
default = ["encode"]

## Support encoding ID3 tags
encode = []

