[package]
name = "id3"
version = "0.2.3"
authors = [
    "James Hurst <jh.jameshurst@gmail.com>",
    "polyfloyd <floyd@polyfloyd.net>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jameshurst/rust-id3"
documentation = "https://jameshurst.github.io/rust-id3"
description = "A library for reading and writing ID3 metadata"
keywords = ["id3", "audio", "parser", "metadata"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]

[features]
default = []
unstable = []

[dependencies]
bitflags = "1.0.3"
byteorder = "1.2.3"
clippy = { version = "0.0.*", optional = true }
derive_builder = "0.5.1"
encoding = "0.2.33"
flate2 = "1.0.1"
lazy_static = "1.0.0"
regex = "1.0.0"

[dev-dependencies]
tempdir = "0.3.5"
