[package]
name = "id3"
version = "0.3.0"
edition = "2018"
authors = [
    "James Hurst <jh.jameshurst@gmail.com>",
    "polyfloyd <floyd@polyfloyd.net>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jameshurst/rust-id3"
documentation = "https://jameshurst.github.io/rust-id3"
description = "A library for reading and writing ID3 metadata"
keywords = ["id3", "audio", "parser", "metadata"]
include = ["src/*", "Cargo.toml", "LICENSE", "README.md"]

[features]
default = []
unstable = []

[dependencies]
bitflags = "1"
byteorder = "1"
derive_builder = "0.7"
encoding = "0.2"
flate2 = "1"
lazy_static = "1"
regex = "1"

[dev-dependencies]
tempdir = "0.3"
