name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update
    - run: sudo apt install -y ffmpeg
    - run: rustup update
    - run: cargo build
    - run: cargo test --all-features

  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt -- --check
    - run: cargo clippy
    - run: "! grep -r 'dbg!' ./src"

  conventional-commits:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: pip3 install -U Commitizen
      # The commit hash here is that of the commit where we started using conventional commits.
    - run: cz check --rev-range 16610ddb..HEAD
